name: deploying to lambda
on:
  push:
    branches:
    - main
    
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: listing files in repository
      run: ls -l
    - name: zip the code
      run: zip -r python.zip  lambdafunction.py
    - name: listing files in repository  
      run: ls -l
    - name: aws cli version
    - run: aws --version
